### PR TITLE
New York Times Clone Page

### PR DESCRIPTION
**Pull request by alexander16108**
# project page
>>in this project I cloned a web page on which we are asked to make a page on The New York Times and a user experience where user experience the feel of a well-integrated website

tools used:

- git 

- linters

- code editor(visual code)

 
#AUTHOR
>>@alexander16108

doing a project page given by microverse

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @alexander16108 

Welcome to Microverse :tada: and congratulations on submitting your first project.
Your projects do not meet the requirements, as such, you will have to make some changes and submit for another review

**Required Changes are mandatory changes you need to make before your project can be approved while Optional changes are nice-to-haves or recommendations which would not stop your projects from getting approved.**

## REQUIRED

* [x] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] The Pull Request should have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] The **header.html** file should be renamed to **index.html** since it's the home page.
- [x] The file that contains your styles should also be renamed to **style.css**
- [x] You have **styyleing** as the file name but you added **style.css** to your html file as the file that contains the link.

### Make those changes and submit for another code review.
### Please, make sure you submit the same pull request link. Do not create a new pull request!


## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by alexander16108 — COMMENTED** [review]
updated file

**Review by alexander16108 — COMMENTED** [review]
changes implemented

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @alexander16108 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/100484970-3d2ce900-3120-11eb-8054-783666ce2215.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)
- [x] The Pull Request should have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Remove **a.html** and **a.css** files.
- [ ] Article content should be aligned in the center link source page.
- [ ] Headings **(Prerequisites Setup Install Usage Run tests Deployment)** in the README file has no description.
- [ ] **The page has 3 nabar, 3 footer and 3 articles please manage them according to standards** (see [video](https://www.awesomescreenshot.com/video/1877377?key=ea114b912892015d3e494a5d4375228d))


### Navbar
- [ ] Please manage the navbar like original page

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://rawcdn.githack.com/alexander16108/times-article/16f7041004ac35efc77423397355ad8970de26fa/index.html)|
|:---:|:---:|
|source-page|clone|

### The Theory of Inflation
- [ ] Please manage **The Theory of Inflation** section like the original page

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://rawcdn.githack.com/alexander16108/times-article/16f7041004ac35efc77423397355ad8970de26fa/index.html)|
|:---:|:---:|
|source-page|clone|
### Footer
- [ ] Please design the footer like the original footer

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://rawcdn.githack.com/alexander16108/times-article/16f7041004ac35efc77423397355ad8970de26fa/index.html)|
|:---:|:---:|
|source-page|clone|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @alexander16108 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
